### ISSUE TITLE
Suggestion: remove login timeout

### ISSUE THREAD

**Issue by milankragujevic** [kylon/Sharedown#1]
My organization uses an external SSO provider on login, so it can happen that during the many redirections between Microsoft and the SSO provider that Sharedown times out and closes the Chromium worker. So you should increase the timeout to 120 seconds or remove it.

Also it would be nice to store the access token for some time in the app to prevent a convoluted login process with 2FA when using an external SSO provider.

**Comment by kylon** [comment]
timeout should be solved in sharedown 1.0.3

about the access token, sharedown is generating the video url from data on the page, so saving the access token would make no difference.
in this case, i think sharedown needs the chrome data folder.
this may require some time since i'm busy with university

**Comment by palmerj** [comment]
I'm getting a timeout in version 1.0.3 after a very small amount of time, and I'm using a SSO login. I agree this needs to be improved.

**Comment by kylon** [comment]
> I'm getting a timeout in version 1.0.3 after a very small amount of time, and I'm using a SSO login. I agree this needs to be improved.

is the timeout set to 0?

**Comment by palmerj** [comment]
Ah no. I will try that next time.

**Comment by ppfans** [comment]
same timeout issue in version 1.0.4. It seems timeout cannot be changed (30s always) even I set the timeout to 0 or 300000 (it appears changed but no).  It's possible for a longer default timeout? Thanks!
