### ISSUE TITLE
3.5.4 3.5.4 yt-dlp doesnt work, direct works

### ISSUE THREAD

**Issue by VooDisss** [kylon/Sharedown#109]
Getting
ERROR: batch file yt-dlp-channels.txt could not be read
Pathway to yt-dlp is declared properly in my Windows 10 PATH settings, i can use yt-dlp with other software and in CMD, but not here...
--ignore-config argument you need to put into the software to fix this I think... I can't do it

**Comment by VooDisss** [comment]
Fixed this by downloading a new version of yt-dlp.exe where it is declared (my system did not take into consideration that I installed a new one through powershell)

**Comment by VooDisss** [comment]
Nevermind, the yt-dlp method does not work (again? IDK if it started working then, maybe just a fluke).
Delete issue if its not in proper order, im sorry.

**Comment by kylon** [comment]
direct will only work in few cases, what is the error with yt-dlp

**Comment by VooDisss** [comment]
Already fixed yt-dlp. Tutorial how to do it:
open cmd, write `where ffmpeg` and `where yt-dlp`, then look if they are in a place like for me:
`C:\Users\Username\AppData\Local\Microsoft\WinGet\Links\ffmpeg.exe`
`C:\Users\Username\AppData\Local\Microsoft\WinGet\Links\yt-dlp.exe`
If yours is in some random folder from sometime earlier - clean it up. 

Cleaning up:
Go to your system PATH settings, look at the settings for user PATH and look for wrong directory that leads to your old ffmpeg and yt-dlp (you know those directories from earlier commands)
Delete those directories from the list and yt-dlp and ffmpeg inside them. 

Open powershell with admin permissions and write:
`winget install yt-dlp`
`winget install ffmpeg`

In user PATH settings, add a path to "C:\Users\Username\AppData\Local\Microsoft\WinGet\Links" 
Done, now it should work... It fixed things for me, now both direct and yt-dlp method work.
Thanks for the awesome software, kylon!
