### ISSUE TITLE
Puppeteer Error

### ISSUE THREAD

**Issue by Imma-P** [kylon/Sharedown#11]
When I try to download a video, I get this error:

waiting for selector 'input[type="text"]' failed: timeout 30000ms exceeded

**Comment by Imma-P** [comment]
I just realized this only happens if Sharedown login module is set on "University [Simple]"

**Comment by kylon** [comment]
that means your login page is different and a new module is required to enable auto-login for that

**Comment by Imma-P** [comment]
> that means your login page is different and a new module is required to enable auto-login for that

Ok. Thank you
