### ISSUE TITLE
Can't download folder, but can download otherwise

### ISSUE THREAD

**Issue by VooDisss** [kylon/Sharedown#111]
Using windows 10
Getting error "unknown folder URL". 
Tried compiling from source with `npm i` and `npm start` - same result (apart of error can't find chromium, which I somehow fixed on my part)

Tried also installing 3.5.4 version - same result "unknown folder URL".

**Comment by kylon** [comment]
what is the url like?

**Comment by VooDisss** [comment]
Url is like this:
https://school-my.sharepoint.com/personal/name_surname_school/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fname_surname_school%2FDocuments%2F%C4%AEra%C5%A1ai&FolderCTID=0x9999999994B740E68B1E478C3F755ABB5B2D4S&view=0

**Comment by kylon** [comment]
are you getting this from folder `right click -> copy url` in sharepoint?

**Comment by VooDisss** [comment]
I'm getting this URL from the top bar (link when I'm in the folder)...
Now I used microsoft teams and entered into a team and it has a folder shared with recordings of its meetings:
The link is a bit different:
`https://school.sharepoint.com/:f:/s/dr.namesurname/tJUSdvzrYvliO3ab2r0DuImYWEyEB-OHadg-MId6InYuyA?e=VG7YVQ`
But still throws the same error...

Please test if folder download is working for you (and on which version) and please give an example how a working link should look like.

**Comment by kylon** [comment]
fixes url error, should work

[sharedownt.zip](https://github.com/user-attachments/files/18103191/sharedownt.zip)

don't use urls from address bar, get them from sharepoint context menu

**Comment by VooDisss** [comment]
It worked, now no more hassle by doing it one after another!

Are you planning to merge this fix into a newer version? I wonder what is the reason it did not work in previous versions then... Thank you!
The error which I ignored:
![image](https://github.com/user-attachments/assets/00968b68-2054-4251-a503-8555494b3385)
Also output in regular and admin rights cmd for `npm i` and `npm start` shows this `access is denied`:
![image](https://github.com/user-attachments/assets/fc22ce31-82ad-456c-ae13-597a26a8edfc)

**Comment by VooDisss** [comment]
How do I download whole directory that is shared?

If the files are not put into a folder I cannot obtain a "folder link" and all I can do is just manually getting all of the links (but if they were in a folder, then it would be easy)

Is there any trick to do it?

The files are just shared for certain users but the root folder which they sit inside is not accessible (maybe all the different classrooms have the same folder and the permissions are distributed different for each file (for each class)), thus again - i can't get the folder link...

**Comment by kylon** [comment]
yes, i ll pack a new version later

permission issues should be solved in your side, maybe more than one sharedown process was running or there are broken permissions in your folders, check both task manager and folder permissions
you don't need admin for npm commands




> How do I download whole directory that is shared?
> 
> If the files are not put into a folder I cannot obtain a "folder link" and all I can do is just manually getting all of the links (but if they were in a folder, then it would be easy)
> 
> Is there any trick to do it?
> 
> The files are just shared for certain users but the root folder which they sit inside is not accessible (maybe all the different classrooms have the same folder and the permissions are distributed different for each file (for each class)), thus again - i can't get the folder link...

i ll check this case, as of now, you need to get each video url or ask for the folder link, i'm no longer using sharepoint since few years, if there are new permission modes, it is possible folder import cannot be used in this case
