### ISSUE TITLE
Puppeteer Error: Network Error

### ISSUE THREAD

**Issue by tipicoenlauniFB** [kylon/Sharedown#15]
Hi! When I'm trying to download any video, I get this error:
Puppeteer Error: Network Error
Only with Login required videos

I tried to download in different devices with different Internet conection... but I had the same error.

**Comment by kylon** [comment]
[Sharedown-t1.zip](https://github.com/kylon/Sharedown/files/7446299/Sharedown-t1.zip)

download latest nodejs from [here](https://nodejs.org/dist/v17.0.1/node-v17.0.1-x86.msi)
unpack _sharedown-t1_
open cmd in unpacked folder
type `npm i` to download the required dependencies (only once)
type `npm start` to run sharedown

please try again with this test version and if you still get an error, attach a new log.

**Comment by tipicoenlauniFB** [comment]
@kylon it works. Thanks a lot!

**Comment by kylon** [comment]
[Sharedown-t2.zip](https://github.com/kylon/Sharedown/files/7447737/Sharedown-t2.zip)

yeah, that was a quick test, this is the fix, please try again

**Comment by tipicoenlauniFB** [comment]
@kylon It works perfectly
