### ISSUE TITLE
Persistent login credentials?

### ISSUE THREAD

**Issue by jtojnar** [kylon/Sharedown#17]
Would it be a bad idea to store the Microsoft ID permanently?

And also to store the credentials for the _university_ login module in the system keyring (e.g. using https://github.com/atom/node-keytar)?

Unfortunately, my university has the SSO set up in such a way that enabling chrome userdata will not preserve the sign in (probably logs out on browser exit).

**Comment by kylon** [comment]
weird
yes, i think it can be added
