### ISSUE TITLE
Network Error

### ISSUE THREAD

**Issue by palmerj** [kylon/Sharedown#2]
I add my URL, click Start download, then login in via SSO+MFA, and it seems to login ok, but once the chrome session ends and I go back to the main sharedown dialog I get "Network Error".  There is nothing in the Logs to tell me why the error occurred. 

<img width="912" alt="error" src="https://user-images.githubusercontent.com/580022/124531355-aa8cbf00-de51-11eb-9dab-37356e08fedc.png">

Note, I'm on MacOS 11.4 using 1.0.3

**Comment by kylon** [comment]
yt-dlp or ffmpeg? have you tried with both?

**Comment by palmerj** [comment]
I have both installed on my Mac:

```
% yt-dlp --version
2021.06.23

 % ffmpeg -version
ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
built with Apple clang version 12.0.5 (clang-1205.0.22.9)
configuration: --prefix=/usr/local/Cellar/ffmpeg/4.4_2 --enable-shared --enable-pthreads --enable-version3 --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libspeex --enable-libsoxr --enable-libzmq --enable-libzimg --disable-libjack --disable-indev=jack --enable-avresample --enable-videotoolbox
libavutil      56. 70.100 / 56. 70.100
libavcodec     58.134.100 / 58.134.100
libavformat    58. 76.100 / 58. 76.100
libavdevice    58. 13.100 / 58. 13.100
libavfilter     7.110.100 /  7.110.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  9.100 /  5.  9.100
libswresample   3.  9.100 /  3.  9.100
libpostproc    55.  9.100 / 55.  9.100

```

**Comment by kylon** [comment]
I mean, do you get this error with both?

**Comment by palmerj** [comment]
How do you choose which one to use? That's not clear to me. I already had both installed, so I don't really want to uninstall one of them. Cheers

**Comment by palmerj** [comment]
Ok sorry I see it in the options. Trying now

**Comment by palmerj** [comment]
Ok. I've tried both options and still get a network error.

**Comment by palmerj** [comment]
@kylon any ideas?

**Comment by kylon** [comment]
sorry, busy with life

attached a version with more logs

* unpack
* open a terminal in unpacked folder
* type: _yarn (or npm) install_
* type: _yarn (or npm) start_

set FFMPEG as downloader in settings
start the download and wait for the error
you should see a **testlog.txt** file

remove any sensible data and post it here

[Sharedown-test.zip](https://github.com/kylon/Sharedown/files/6808129/Sharedown-test.zip)

**Comment by mtae** [comment]
So this is the error message that pops up
![image](https://user-images.githubusercontent.com/6492350/127106456-4eb819d1-6eae-4264-82a5-db048be7783e.png)


and the logs have a url of the form

https://northcentralus1-mediap.svc.ms/transform/videomanifest?provider=spo&inputFormat=mp4&cs=fFNQTw&docid=&access_token=<some characters>.<Lots of characters>.<some characters>&action=Access&part=Index&format=dash&useScf=True&pretranscode=0&transcodeahead=0
Which when accessed returned an error that the uri can't be null (presumably the docid) 


Tried using a different kind of Share URL as well

**Comment by kylon** [comment]
can you see your docid in logs? (as variable or as value)

new test
[Sharedown-test.zip](https://github.com/kylon/Sharedown/files/6902006/Sharedown-test.zip)
 and attach the full log file?

**Comment by kylon** [comment]
@s-bhagwat 
see also **resp data dump** in log, you may not see **docid** word there but you should look for a variable that contains the docid

**Comment by s-bhagwat** [comment]
@kylon here is some data 
 {      "ID": "563",
        "PermMask": "0x1003008031001",
        "FSObjType": "0",
        "HTML_x0020_File_x0020_Type": "Media.Meeting",
        "UniqueId": "{AACACCF6-28D2-4657-B902-B96D020FD382}",
        "ProgId": "Media.Meeting",
        "NoExecute": "1",
        "ContentTypeId": "0x01010085D2E0551D9086498952A258B92E404D",
}

**Comment by kylon** [comment]
thats the full object?

anything like {.spItemUrl}?

**Comment by s-bhagwat** [comment]
".spItemUrl": "https://collagenameoffice-my.sharepoint.com:443/_api/v2.0/drives/b!bqDrShpqBkahIdfHwvIOxJqJ3_fbZqJOv-MJezIPEgVr0ncgmuTPQoYBiNq5xnnJ/items/01444GO7PWZTFKVURIK5DLSAVZNUBA7U4C?version=Published",

**Comment by s-bhagwat** [comment]
does the resp data start with {"something":"","Templates":{},"ListData":{?
yes

after runnig with new test
are _makeVideoManifestFetchURL and _getFileName: url the same string?
yes
there is no make url error

**Comment by kylon** [comment]
[sharedown-t4.zip](https://github.com/kylon/Sharedown/files/6933692/sharedown-t4.zip)

any `make url error:` error?

**Comment by s-bhagwat** [comment]
make url error: empty value

**Comment by kylon** [comment]
ah, i forgot to print the name

sorry, rerun
[sharedown-t5.zip](https://github.com/kylon/Sharedown/files/6934067/sharedown-t5.zip)

these are the variable names
```
url variable = resp data variable

'{.mediaBaseUrl}' = '.mediaBaseUrl'
'{.callerStack}' = '.callerStack'
'{.spItemUrl}' = 'CurrentFolderSpItemUrl'
'{.driveAccessToken}' = '.driveAccessToken'
```

look for the resp data variable in resp data, is it missing?
if no, can you post the dump without your data?

**Comment by kylon** [comment]
Can you explain so that this issue can be fixed?
What is the variable?

**Comment by s-bhagwat** [comment]
Which variable? Am I supposed to tell you my access token?

**Comment by palmerj** [comment]
> sorry, busy with life

No probs at all. Me too!

> remove any sensible data and post it here

Please find my log [here](https://gist.github.com/palmerj/425cc951a3a4224c3bb2ae3dd8d4070b). Note I used sharedown-t5.zip and it's still not downloading for me.

**Comment by kylon** [comment]
> Please find my log [here](https://gist.github.com/palmerj/425cc951a3a4224c3bb2ae3dd8d4070b). Note I used sharedown-t5.zip and it's still not downloading for me.

Thanks, this helps a lot
I ll take a look tomorrow

**Comment by kylon** [comment]
@palmerj 
this should work

[sharedown-t6.zip](https://github.com/kylon/Sharedown/files/6954979/sharedown-t6.zip)

**Comment by palmerj** [comment]
Thank heaps, the download has started! 

I'm noticing that the download is taking some time and only going at ~400kbps, and I have much more bandwidth. Is this download somehow rate limited, or could it be speed up by downloading multiple chunks at once?

**Comment by palmerj** [comment]
Actually now the download has stalled at about 25%. I'm looking at network traffic and there is nothing coming from the node progress at all.

**Comment by palmerj** [comment]
Ok I restarted and it's worked - got 150mb mp4 file. Still slow to download. Maybe there is some sort of deadlock going on...

**Comment by kylon** [comment]
the stream is not as fast as a regular download, MS introduced some limits recently
yt-dlp downloads multiple chunks at once, actually 5
if you get stuck too many times i think your only option is ffmpeg for that video, i am not sure if it is a yt-dlp issue or MS 

anyway, if you confirm this issue has been solved, i ll release a new version to close this.

**Comment by palmerj** [comment]
Thanks. I retested with yt-dlp and it's much faster. I'm happy. Please release a new version.
