### ISSUE TITLE
The command Copy / Paste doesn't work on Mac OSX Big SUR 11.6.1

### ISSUE THREAD

**Issue by fajota2** [kylon/Sharedown#23]
Hello!

I tried to use your last version app, but the command Copy / Paste does'nt work on Mac OSX Big SUR 11.6.1 :(

I downloaded the file, but I needed type all the URL :D

#bug

**Comment by kylon** [comment]
you mean the copy button of each video or copy/paste in add text input?
intel mac or arm?

**Comment by fajota2** [comment]
Intel Mac - copy/paste in add text input

**Comment by LoSunny** [comment]
Same here, it is because there isn't a "copy" and "paste" menu item in Sharedown. Furthermore we cannot close the app by "CMD+Q" because there isn't an option to close the app in the menu
![image](https://user-images.githubusercontent.com/25066078/149274154-2bc42538-86bf-4fd3-9f8c-1def71393b77.png)
