### ISSUE TITLE
Throttle.htm error while using youtube-dlp downloader

### ISSUE THREAD

**Issue by maffinyep** [kylon/Sharedown#27]
idk if this error could be handled client-side, I'm reporting it just for the record 🙊
[https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online](https://docs.microsoft.com/en-us/sharepoint/dev/general-development/how-to-avoid-getting-throttled-or-blocked-in-sharepoint-online)

**Comment by kylon** [comment]
lower this value when this occurs

![2022-01-22-094525_485x111_scrot](https://user-images.githubusercontent.com/3252255/150631577-3bd6ae37-7ff3-41e9-acab-5f836953b12f.png)
