### ISSUE TITLE
Sharedown not detecting ffmpeg installation on Apple Silicon

### ISSUE THREAD

**Issue by gmonteir** [kylon/Sharedown#28]
Guessing this has something to do with how Homebrew installs packages to /opt/homebrew by default on Apple Silicon

**Comment by kylon** [comment]
i don't have an arm mac to test this, what is the path to the ffmpeg bin?
i can add that to sharedown and it should find ffmpeg

**Comment by gmonteir** [comment]
Actually it appears that this function in preload.js is throwing an error:

    api.hasFFmpeg = () => {
        const proc = require('child_process');

        try {
            proc.execSync('ffmpeg -version').toString();
            return true;

        } catch (e) {}

        return false;
    }

The path to ffmpeg is `/opt/homebrew/bin/ffmpeg` (same for yt-dlp).

**Comment by kylon** [comment]
do you have the error message? probably because it cannot find ffmpeg

added homebrew path
[Sharedown.zip](https://github.com/kylon/Sharedown/files/8062540/Sharedown.zip)

**Comment by gmonteir** [comment]
Getting a spinning wheel now:
<img width="912" alt="Screen Shot 2022-02-14 at 9 03 21 AM" src="https://user-images.githubusercontent.com/26098913/153911279-e5351b74-d6e0-4b69-94fe-796cae349d77.png">
