### ISSUE TITLE
 Download failed -> Invalid data found when processing input

### ISSUE THREAD

**Issue by luciomarcomaranta** [kylon/Sharedown#29]
I'm trying to download a View Only video but I'm having problems with all the downloader.

With Yt-dlp and Direct I'm having:
Download failed
YT-dlp error:
Exit code: 1

With Ffmpeg:
Invalid data found when processing input

**Comment by kylon** [comment]
can you post a log?

**Comment by kylon** [comment]
closed for inactivity
