### ISSUE TITLE
Improovement: download all the video URLS, in chronological order

### ISSUE THREAD

**Issue by FraH90** [kylon/Sharedown#34]
Hi guys, I've appreciated the new functionality to import all the URLs and download all the videos, without doing copy/past of every single URL.

However, due to the fact that the videos I need to download aren't numbered (Lesson 1, 2, 3, etc) I need to order them in chronological order, so downloading as first the first recorded video the timestamp of each file will give me a method to order the videos in chronological order. 
This is possible, currently, only copying each single video URL from the sharepoint webpage, by selecting "order by date", but not with the tool you're provided in sharedown (which will order the URLs in alphabetic order).

Is it possible to implement this functionality in the URL importer? Import the URLs from a folder in chronological order, putting as first the first recorded video? You will save me a lot of time, really.

**Comment by mikedepetris** [comment]
It would be a useful option, but I am not sure if it is the case to add complexity in additional features. About the specific use case, it happened to me to stop sharedown, open the json configuration file (sharedown.state if I remember well) and reorder the queue elements with a json editor, maybe VScode.

**Comment by kylon** [comment]
I can take a look, iirc a timestamp is available in the data sharedown gets, if it is the case should be easy to add

**Comment by FraH90** [comment]
> I can take a look, iirc a timestamp is available in the data sharedown gets, if it is the case should be easy to add

Thank you, it would be really helpful if implemented
