### ISSUE TITLE
Even though there's the possibility, you can't actually download multiple files

### ISSUE THREAD

**Issue by Elvino00** [kylon/Sharedown#36]
When i start the download of multiple files in one time (for example 3 files), i can download one file, but then the second one it's stuck nearly at the end. So i close the software and when i reopen it and try to redownload the files (link are already stored in the software from the previous attempt) it gets stuck again. I am on windows 10 x64 bit version 21H2.

**Comment by kylon** [comment]
it gets stuck on the same file or always on 2nd download?
what downloader?
can you attach logs?

**Comment by Elvino00** [comment]
> it gets stuck on the same file or always on 2nd download? what downloader? can you attach logs?

Always on second download. The software i use is sharedown 4.2.0 portable.

**Comment by kylon** [comment]
thanks, i was able to reproduce, i ll work on a fix

**Comment by kylon** [comment]
[Sharedownt.zip](https://github.com/kylon/Sharedown/files/8837214/Sharedownt.zip)

unpack
open cmd and type `npm i` or `yarn install`
to run type `npm start` or `yarn start`

**Comment by Elvino00** [comment]
> thanks, i was able to reproduce, i ll work on a fix

Wow, I'm relieved.

**Comment by kylon** [comment]
can you please run the test version above and let me know?

**Comment by Elvino00** [comment]
> can you please run the test version above and let me know?

yes, I'm installing the necessary things to install it.

**Comment by Elvino00** [comment]
> can you please run the test version above and let me know?

I'll try with 3 downloads simultaneously without logging and in case something goes wrong, I'll renable logging

**Comment by kylon** [comment]
good, the error should be fixed

**Comment by Elvino00** [comment]
> good, the error should be fixed

Are you going to make a new release? Should I close the issue?

**Comment by kylon** [comment]
yes, new release later today
issue will be closed automatically with new release

**Comment by Elvino00** [comment]
> yes, new release later today issue will be closed automatically with new release

Thanks for your work. I feel relieved this error has been solved.
