### ISSUE TITLE
Login error.

### ISSUE THREAD

**Issue by MagicWRR** [kylon/Sharedown#38]
![Immagine 2022-06-14 215753](https://user-images.githubusercontent.com/64907191/173678326-2ed90fdd-2452-4873-b12e-30497cb43d8f.png)
Hi I installed the Sharedown this afternoon with all the dependencies, but when I paste the link and start the download after it tries the authentication it gives me this error. What can I do?

**Comment by kylon** [comment]
what login module are you using?

they are not universal, things may be different for your login page and so it would need its own logind module for automatic login

**Comment by MagicWRR** [comment]
I am using the form for microsoft 365.

**Comment by MagicWRR** [comment]
I changed the form to simple university and it gives me this error now, after logging into my account it always reloads the same page until chromium closes.
![image](https://user-images.githubusercontent.com/64907191/173762902-76289451-f1c1-410f-85fe-0ec1ba8533df.png)

**Comment by MagicWRR** [comment]
Or when i use unima the error is this. 
![image](https://user-images.githubusercontent.com/64907191/173763276-0588df09-6119-412f-9995-842afbfbef31.png)

**Comment by MagicWRR** [comment]
Ok, sorry for that, my university use microsoft 356, I have enabled logs but where i can find them?

**Comment by kylon** [comment]
Ok, so  can be closed?

**Comment by MagicWRR** [comment]
yes
