### ISSUE TITLE
Login page refresh periodically

### ISSUE THREAD

**Issue by massimostanzione** [kylon/Sharedown#39]
Login page, with Microsoft (University) login, automatically refreshes each 7 seconds, whether mail/password are inserted or not. The only way to avoid this is to type and enter credentials in less than 7 seconds. After three refreshes, `Pupeeter error`/`Unable to find a valid donor response!`

Version 4.2.2, on Linux Mint 20.2

Settings:
- `Sharedown login module`: `Basic - Manual login`
- `Microsoft ID`: inserted

**Comment by massimostanzione** [comment]
Update: changing the value of `Sharedown login module` (and setting mail/password fields):
- `University [MS 365]`: no problem, but I have to manually type the password, and the download does not start because of the same error message of [this other issue](https://github.com/kylon/Sharedown/issues/35#issuecomment-1130241742)
- `University [Simple]`: it simply works (or, at least, I never have to wait 7 seconds)

**Comment by kylon** [comment]
a regression from 0f645bef6a5fe79cb9f635d907281dc49f1ae064

i ll work on it and attach a test version here

**Comment by massimostanzione** [comment]
Done, tried all the settings combinations mentioned above and the timeout problem seems **fixed** now.
_(just for the record, still present the [issue](https://github.com/kylon/Sharedown/issues/39#issuecomment-1159014714) with `Sharedown login module`: `University [MS 365]`)_.

Thank you!

**Comment by massimostanzione** [comment]
> login modules are not universal, if you have to type the password means your login page has different input, and according to what you say the simple login module is working so that is the one compatible with your login page

Oh yes, now that I think about it I was convinced that my login had something to do with MS365, nevermind :)

> about the response error, you get that only with ms 365?

Yes, the other methods work without any issue.

**Comment by kylon** [comment]
ok, i think it is just the wrong module causing the error.

i ll push a new release later today with the fix above, thanks for testing.
