### ISSUE TITLE
With the introduction by my university of the 2FA for my school account, I can't download anything

### ISSUE THREAD

**Issue by Elvino00** [kylon/Sharedown#40]
In order to download videos from sharepoint I use the option "Unina" as login module. The problem is that right today, my university forced the 2FA on all account so I had to login again in all my devices. The point is, when I try to download a video (right after clicking the download button) , The chromium windows is opened, the email address is automatically inserted but it asks me the code i received via phone for the 2FA. The point is that I can't even write in the code that the page reloads by itself and asks me how i want to authenticate for 2FA.  

Attached to this issue, here are the [logs](https://github.com/kylon/Sharedown/files/8943679/sharedownLog.log).

**Comment by kylon** [comment]
[Sharedownt1.zip](https://github.com/kylon/Sharedown/files/8956537/Sharedownt1.zip)

unpack
open a terminal in unpacked folder
type `npm `i or `yarn install` to download required files
type `npm start` or `yarn start` to start sharedown

**Comment by Elvino00** [comment]
It works and i think that [ytdlp.log](https://github.com/kylon/Sharedown/files/8958244/ytdlp.log) and [sharedownLog.log](https://github.com/kylon/Sharedown/files/8958245/sharedownLog.log) can confirm it. The point is, it always asks for 2FA codes. Isn't there a way to insert the code one time? Because when sharedown opens chromium and I get the message "Do you want to remember login details?" and i click on the tick "don't make this message appear again" and then on the "yes" button, i always get the 2FA code asked

**Comment by kylon** [comment]
Yes, enable the use of chrome data folder, that will save your login session while sharedown is running.

That option will disable auto login, so you have to perform a manual login and when asked to remember login credential you must say `Yes`.

From now on, until you close sharedown, no more login should be needed

**Comment by Elvino00** [comment]
> Yes, enable the use of chrome data folder, that will save your login session while sharedown is running.
> 
> That option will disable auto login, so you have to perform a manual login and when asked to remember login credential you must say `Yes`.
> 
> From now on, until you close sharedown, no more login should be needed

There is a problem: the [option](https://postimg.cc/K49WxnLX) is disabled and can't be enabled.

**Comment by Elvino00** [comment]
> Set login module to basic

Just done. The option is still of and can't be enabled

**Comment by kylon** [comment]
What other options are enabled
Send a screen, there is one that must be disabled for that to be enabled

**Comment by Elvino00** [comment]
[](url)

> What other options are enabled Send a screen, there is one that must be disabled for that to be enabled

I've found the option to be disabled in order for the chrome userdata to be enabled but I don't even have the time to write my email that the pages reloads.

**Comment by kylon** [comment]
Ok, i ll look into this

**Comment by Elvino00** [comment]
> Yea, its not that, you get that as a result

Ok, I'll wait for your next answer.

**Comment by kylon** [comment]
[Sharedownt2.zip](https://github.com/kylon/Sharedown/files/8959588/Sharedownt2.zip)

**Comment by Elvino00** [comment]
> [Sharedownt2.zip](https://github.com/kylon/Sharedown/files/8959588/Sharedownt2.zip)

I saw the new package. I'm gonna test it

**Comment by Elvino00** [comment]
> > [Sharedownt2.zip](https://github.com/kylon/Sharedown/files/8959588/Sharedownt2.zip)
> 
> I saw the new package. I'm gonna test it
> 
> EDIT: The package works and here are the logs if you wanna check them out. [ytdlp.log](https://github.com/kylon/Sharedown/files/8965419/ytdlp.log) [sharedownLog.log](https://github.com/kylon/Sharedown/files/8965420/sharedownLog.log)
> 
> By following your suggestion the phone 2FA authentication works and i can keep my data and not put them in every time.

don't know if you've received any notification about the edits, in case I make a new comment

**Comment by kylon** [comment]
ok, i ll make a new release, thanks
