### ISSUE TITLE
OnePlayer Container Error while downloading

### ISSUE THREAD

**Issue by xmaionx** [kylon/Sharedown#42]
waiting for selector OnePlayer Container failed timeout 10000ms exceded

**Comment by kylon** [comment]
can you explain what are steps to get that? in which page?

**Comment by Elvino00** [comment]
> can you explain what are steps to get that? in which page?

I got the same error he said. So here's what happens: i put multiple downloads to download and suddendly i find a chromium windows telling me that there was an error in getting the resource (i can't actually recall well what it actually said). So I refresh the window hoping that the problem gets solved and boom, you get the error the guy says (and i also posted an image of that). I attached logs too.

![image](https://user-images.githubusercontent.com/74961430/180600810-4291f790-7f37-4b2e-85c9-5aa6b9a9b91c.png)
[ytdlp.log](https://github.com/kylon/Sharedown/files/9173527/ytdlp.log)
[sharedownLog.log](https://github.com/kylon/Sharedown/files/9173528/sharedownLog.log)

**Comment by kylon** [comment]
that error is unrelated but i ll increase the timer, the real error could help, there is nothing in logs so i suppose a puppeteer error?

**Comment by Elvino00** [comment]
> that error is unrelated but i ll increase the timer, the real error could help, there is nothing in logs so i suppose a puppeteer error?

Yeah, i think.

**Comment by niXta1** [comment]
Getting the same error on macOS here...

**Comment by kylon** [comment]
> Getting the same error on macOS here...

see #45
