### ISSUE TITLE
saving partial results?

### ISSUE THREAD

**Issue by gg4u** [kylon/Sharedown#47]
I am experiencing this issue with some videos.
The download of fragments works until the end of both video and audio streams, but just at the merging of the two, there is an error (I cannot tell if the error is in the merging or in the last bit of audio, I only see an exit 1 error).

I think it could be useful an option to persist the two tracks, instead of removing them from the temporary folder, so that one may attempt to fix it later or to inspect if some of the two tracks are somehow corrupted that prevent a final merge.
What do you think?

Note the error occurred with default throttling, I m trying to lower it and see if something change.

P.s. can you explain what throttling is and how it affects in this context ?

**Comment by kylon** [comment]
Throttle option is for when you get blocked by sharepoint because of too many downloads

The issue you describe sounds like #20 and the others open about this

Are you using latest ytdlp?
I can add an option to disable automatic delete on error

**Comment by kylon** [comment]
Hm, yea i can try that, iirc there is an option to not generate fragments but merge the file while downloading (it still gives you error) but you end up with a video file
I dont remember tho if when i tried the file was valid after the error
