### ISSUE TITLE
While downloading multiple files i got this error "Protocol error (Runtime.callFunctionOn): Target closed

### ISSUE THREAD

**Issue by Elvino00** [kylon/Sharedown#48]
I was downloading multiple files and when the chromium windows opens up, i get this error:

![image](https://user-images.githubusercontent.com/74961430/180640030-9dce23a2-8915-4a47-8faa-250efb453667.png)

Here are the logs:
[sharedownLog.log](https://github.com/kylon/Sharedown/files/9175441/sharedownLog.log)
[ytdlp.log](https://github.com/kylon/Sharedown/files/9175442/ytdlp.log)

**Comment by kylon** [comment]
mh, from what i found it seems it runs out of memory

using the data folder? after how many downloads?

**Comment by Elvino00** [comment]
> mh, from what i found it seems it runs out of memory
> 
> using the data folder? after how many downloads?

Usually i put max 5 files downloading together, not more. Sometimes sharedown downloads them all without problems, sometimes it arrives to the third, fourth file and it stops with that error

**Comment by kylon** [comment]
can you please try t5 here https://github.com/kylon/Sharedown/issues/45#issuecomment-1217004737

not targetting this one, but changes there may have fixed this

**Comment by kylon** [comment]
this is supposed to be fixed in latest 5.2.1 release
