### ISSUE TITLE
Can't find preload.js on MacOS

### ISSUE THREAD

**Issue by Ferox97** [kylon/Sharedown#50]
I need to edit that to fix a problem but I'm unable to find it...

**Comment by kylon** [comment]
https://github.com/kylon/Sharedown/blob/main/preload.js

edit and rebuild appimage

but if there is a bug, please share so can be fixed for everyone

**Comment by Ferox97** [comment]
How can I rebuild the app? I'm not familiar with that... I've installed the app directly from the .dmg file

About the bug, it's the same one raised in Issue #49

**Comment by kylon** [comment]
you need [nodejs](https://nodejs.org/dist/v18.10.0/node-v18.10.0.pkg) and yarn
you can also use [brew](https://brew.sh/index_it) to install node if you prefer

install nodejs, once done open a terminal and type `npm i -g yarn`

then type
```
git clone https://github.com/kylon/Sharedown.git
yarn install
```

you can now edit and use `yarn dist` to build the dmg

**Comment by Ferox97** [comment]
I'm stuck with yarn dist... it says Couldn't find a package.json file in "/Users/francesco".
I have the cloned repo ready and edited
