### ISSUE TITLE
Failde to launch the browser process (Puppeteer error)

### ISSUE THREAD

**Issue by jathri** [kylon/Sharedown#55]
Hello, updated to last version (5.1.0) and I am stuck with this error:
https://i.imgur.com/yvgdRQi.png
I read https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md but cannot solve issue. Can you please help? Do I need to install Puppeteer separately?
I am Windows 10 user. I have Node.js v16.13.0 installed.

**Comment by jathri** [comment]
Tried to install Puppeteer to both
c:\Users\XXX\AppData\Local\Programs\sharedown\resources\app.asar.unpacked\node_modules\
and 
C:\Program Files\nodejs\node_modules\npm\node_modules\
to no avail. Please help.

**Comment by kylon** [comment]
puppeteer is bundled with sharedown, you cannot install it separately

what windows package are you using? portable or installer?

i can try on my windows install tomorrow

**Comment by jathri** [comment]
Hello,
thank you for your reply.
It is this one: https://i.imgur.com/ZkOtAPS.png
It did not seem that puppeteer was bundled. At least it was not present at: c:\Users\XXX\AppData\Local\Programs\sharedown\resources\app.asar.unpacked\node_modules
Or Sharedown uses yet another folder for puppeteer module?

**Comment by jathri** [comment]
Unfortunately, the issue still persist: https://i.imgur.com/yvgdRQi.png
Can you please look into it once more?

**Comment by kylon** [comment]
are you sure the install was successful? the new package is now correct

try to uninstall and install again
also, try with latest nodejs release [here](https://nodejs.org/dist/v19.0.1/node-v19.0.1-x86.msi)

**Comment by jathri** [comment]
I can confirm that issue still persists. Can you please look into attachment? Is everything as should be?
[sd.pdf](https://github.com/kylon/Sharedown/files/9956366/sd.pdf)

**Comment by kylon** [comment]
looks good

are you using latest nodejs? 19.x

**Comment by jathri** [comment]
Use Node.js v19.0.1. Tried to unistall and install again to no avail. And there is nothing  in logs folder. Please, help.

**Comment by kylon** [comment]
can you try portable version?

**Comment by mattiac2210** [comment]
> Use Node.js v19.0.1. Tried to unistall and install again to no avail. And there is nothing in logs folder. Please, help.

I have the same problem

**Comment by kylon** [comment]
@mattiac2210 @jathri 
please test
https://github.com/kylon/Sharedown/releases/download/5.1.0/sharedown.Setup.5.1.0.exe

**Comment by jathri** [comment]
It works. Thank you for fixing this :)

**Comment by kylon** [comment]
good, i ll push a new release

**Comment by mattiac2210** [comment]
> good, i ll push a new release

It works me too. Thank you very much ;)
