### ISSUE TITLE
Session closed. Most likely the page has been closed.

### ISSUE THREAD

**Issue by closmarfer** [kylon/Sharedown#64]
This error appears in logs over and over when I start the download and the application keeps loading without do nothing:
```
_waitForVideoPlayer: ignore:
Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.

_waitForVideoPlayer: ignore:
Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.

_waitForVideoPlayer: ignore:
Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.
```

Version: Sharedown 5.2.2
MacOS Ventura 13.0.1

**Comment by kylon** [comment]
arm mac? (m1, m2)

**Comment by closmarfer** [comment]
No, is Intel. Thanks

**Comment by kylon** [comment]
anything else in logs?
what happens to the chrome window?

**Comment by closmarfer** [comment]
The Chromium window is closed (I use the builtin Chromium).
I send you some more logs:
```
startDownload: start

startDownload: valid data: true

runPuppeteerGetVideoData: goto https://xxx.sharepoint.com/:v:/r/sites/XXXXXXX.mp4?csf=1&web=1&e=7vbBSz

_sharepointLogin: start login procedure

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

_waitForVideoPlayer: ignore:
Protocol error (Runtime.callFunctionOn): Target closed.

_waitForVideoPlayer: ignore:
Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.

_waitForVideoPlayer: ignore:
Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.

_waitForVideoPlayer: ignore:
Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.

etc. etc.
```

**Comment by kylon** [comment]
are you closing chrome or it quits after login?

probably an issue caused by your login process
try to login, if it gets stuck at video page, press F5 to refresh and wait, it should work

**Comment by closmarfer** [comment]
No, I don't close the page. When I insert user and pass the page redirect to the video, it is showed for a second and the Chromium window is closed automatically and the Sharedown window keeps loading while the log is registered over and over.

I have tried with the Chrome executable and the FFmpeg downloader and it is working. Thanks!
