### ISSUE TITLE
The download does not start

### ISSUE THREAD

**Issue by MattDEV02** [kylon/Sharedown#66]
hello, I have tried in every possible way to download several sharepoint university videos in many different ways but the download does not start. The application screen hangs on loading without doing anything. I used the latest version and 5.0.2

Here is the log:

fillLoginFieldsFromPwdManager: no credentials found for module 0, skip..

startDownload: start

startDownload: valid data: true

WARNING: custom chrome executable, Sharedown may not work as expected!

runPuppeteerGetVideoData: goto https://uniroma3.sharepoint.com/sites/AA2122-CALCOLATORIELETTRONICI-20810074TORLONE/Documenti%20condivisi/Forms/AllItems.aspx?FolderCTID=0x0120005A4E1F6F1F5A7F4D919F47C68AE4795A&isAscending=true&sortField=Modified&id=%2Fsites%2FAA2122-CALCOLATORIELETTRONICI-20810074TORLONE%2FDocumenti+condivisi%2FGeneral%2FRecordings%2FSolo+visualizzazione%2F01+Presentazione+del+corso+e+storia+dei+calcolatori.mp4&viewid=2ea0cc6d-4a14-4265-9fee-267f0979cb25&parent=%2Fsites%2FAA2122-CALCOLATORIELETTRONICI-20810074TORLONE%2FDocumenti+condivisi%2FGeneral%2FRecordings%2FSolo+visualizzazione&web=1

_sharepointLogin: start login procedure

_sharepointLogin: has login data

_sharepointLogin: has msid

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

**Comment by kylon** [comment]
can you try with main instead of release package?

**Comment by MattDEV02** [comment]
I tried:

sharedown.5.2.2.portable.exe
sharedown.Setup.5.2.2.exe
Source code (zip) with npm
sharedown.Setup.5.0.2.exe

**Comment by MattDEV02** [comment]
https://user-images.githubusercontent.com/62772891/221358010-3e215bbf-761c-4280-b7b4-2429eeb5cb94.mp4

**Comment by kylon** [comment]
i mean can you try with latest git?
![2023-02-25-142924_436x318_scrot](https://user-images.githubusercontent.com/3252255/221359528-ae0d6cad-b54d-420c-b084-6484894b82c9.png)

download zip

unpack
open terminal in unpacked folder
run `npm i`
run `npm start` to run sharedown

**Comment by MattDEV02** [comment]
I tried and It didn't work.

My npm version: 9.5.1
Node version: 19.3.0

**Comment by kylon** [comment]
[Sharedown.zip](https://github.com/kylon/Sharedown/files/10831433/Sharedown.zip)

this will open the devtools window, don't close it, try again and post a screen of the console tab when it gets stuck

**Comment by MattDEV02** [comment]
DevConsole (yellow warnings) :  

DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/puppeteer.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/puppeteer-core.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/api.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Browser.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/EventEmitter.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/BrowserContext.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Page.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/JSHandle.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/ElementHandle.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/common.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Accessibility.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/AriaQueryHandler.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/assert.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/AsyncIterableUtil.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/QueryHandler.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/ErrorLike.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Function.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/HandleIterator.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/IsolatedWorlds.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/LazyArg.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Browser.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/ChromeTargetManager.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Connection.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Debug.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/environment.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Errors.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/util.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/ElementHandle.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/GetQueryHandler.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/CustomQueryHandler.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/ScriptInjector.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/injected.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/PierceQueryHandler.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/PQueryHandler.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/TextQueryHandler.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/XPathQueryHandler.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/JSHandle.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/FirefoxTargetManager.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Target.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Page.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/DeferredPromise.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Binding.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/ConsoleMessage.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Coverage.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/ExecutionContext.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Dialog.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/EmulationManager.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/FileChooser.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/FrameManager.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Frame.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/IsolatedWorld.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/LifecycleWatcher.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/NetworkManager.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/DebuggableDeferredPromise.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/HTTPRequest.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/HTTPResponse.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/SecurityDetails.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/NetworkEventManager.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/WaitTask.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/FrameTree.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Input.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/USKeyboardLayout.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/PDFOptions.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/TimeoutSettings.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Tracing.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/WebWorker.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/TaskQueue.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/BrowserConnector.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/fetch.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/BrowserWebSocketTransport.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Configuration.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/ConnectionTransport.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Device.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/NodeWebSocketTransport.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/version.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/PredefinedNetworkConditions.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Product.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Puppeteer.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/PuppeteerViewport.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/TargetManager.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/types.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/node.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/BrowserFetcher.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/agent.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/promisify.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/parse-proxy-response.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/BrowserRunner.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/PipeTransport.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/ChromeLauncher.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/ProductLauncher.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/FirefoxLauncher.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/LaunchOptions.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/PuppeteerNode.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/revisions.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/util.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/getConfiguration.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/Explorer.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/cacheWrapper.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/ExplorerBase.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/loaders.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/getPropertyByPath.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/getDirectory.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/readFile.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/ExplorerSync.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/types.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/index.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/identifier.js.map: Unexpected end of JSON input
DevTools failed to load source map: Could not parse content for file:///C:/Users/matte/Downloads/Sharedown/sharedown/keyword.js.map: Unexpected end of JSON input

Log: 


startDownload: start

startDownload: valid data: true

_getPuppeteerExecutablePath:
ENOENT: no such file or directory, scandir 'C:\Users\matte\Downloads\Sharedown\node_modules\puppeteer\chrome'

runPuppeteerGetVideoData: error
failed to find chromium executable

downloadVideo: has vdata: false

startDownload: failed
undefined

startDownload: start

startDownload: valid data: true

WARNING: custom chrome executable, Sharedown may not work as expected!

runPuppeteerGetVideoData: goto https://uniroma3.sharepoint.com/sites/AA2223-ALGORITMIESTRUTTUREDIDATI-20810078PATRIGNANI2/Documenti%20condivisi/Forms/AllItems.aspx?FolderCTID=0x012000029153846321C041B253E4ADC9F20C60&id=%2Fsites%2FAA2223-ALGORITMIESTRUTTUREDIDATI-20810078PATRIGNANI2%2FDocumenti+condivisi%2FGeneral%2FRecordings%2FSolo+visualizzazione%2FASD_+Lezione+01-20220927_160015-Meeting+Recording+1.mp4&parent=%2Fsites%2FAA2223-ALGORITMIESTRUTTUREDIDATI-20810078PATRIGNANI2%2FDocumenti+condivisi%2FGeneral%2FRecordings%2FSolo+visualizzazione&web=1

_sharepointLogin: start login procedure

_sharepointLogin: has login data

_sharepointLogin: has msid

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

Terminal: 

[5760:0225/160905.899:ERROR:gpu_init.cc(523)] Passthrough is not supported, GL is disabled, ANGLE is

**Comment by kylon** [comment]
[Sharedownt2.zip](https://github.com/kylon/Sharedown/files/10831654/Sharedownt2.zip)

**Comment by MattDEV02** [comment]
Everything like before

https://user-images.githubusercontent.com/62772891/221422283-0faf4d9f-0bb3-4dd3-9d5b-6467c9298e86.mp4

**Comment by MattDEV02** [comment]
I am using chrome executable version 110.0.5481.178

https://user-images.githubusercontent.com/62772891/221436428-28eef95b-ac22-4063-bed2-cb831a01662c.mp4

**Comment by MattDEV02** [comment]
I fixed it, thank you very much
