### ISSUE TITLE
Using YT-dlp as downloader causes a crash after a few downloads because of download bandwidth limitations

### ISSUE THREAD

**Issue by andreafrisina** [kylon/Sharedown#67]
I use sharedown to download several videos in batch. I would be very happy to use _YT-dlp_ as downloader, because it's way faster than _FFMpeg_ (which is unfortunately painstakingly slow).

**_The issue is that I am pretty sure my Uni has set a limitation for the download bandwidth each account can use.
If you exceed the allowed threshold (for example, when using YT-dlp) all your downloads fail and your Sharepoint gets is not reachable for several minutes)._**
I suspect a similar limitation is applied also in other Unis

I have done a lot of tests and I have estimated that this threshold, in my case, is around 2-3 MB/s.

In order to overcome this, **_would it be possible to be able to set a parameter or a slider so you can actually decide which is the maximum download speed for your downloads?_**

I know that a limitation on download speed seems counterintuitive, but this could be a good way to continue using YT-dlp as downloader while not triggering the download bandwidth limitation set by my uni.

**Comment by kylon** [comment]
Hi,

Yes, i see there is a yt-dlp arg that let you set a download speed limit, i ll add a setting for it
