### ISSUE TITLE
"You need permission to access this item"

### ISSUE THREAD

**Issue by YarinSuissa** [kylon/Sharedown#69]
Hi! i just found out about this project, but the idea is awesome and is very much appreciated!

assuming you still have the patience to look at this project from time to time, i came across this issue where it says i don't have permission to see this item while trying to download.

![image](https://user-images.githubusercontent.com/117517623/236681493-3c992445-ede7-46f9-8d04-9579d431e24d.png)

it is worth saying that i am able to watch the VOD of the stream with no issue with this exact link (assuming i'm logged in with my UNI account, which i am while using your program)

any and all thoughts would be appreciated!

**Comment by kylon** [comment]
Hi,

This is after login?

**Comment by stesstesste** [comment]
Hey!

In general you should always check that you are using the microsoft account with permissions to open registration and not a secondary account. That error message is a sign that you are trying to access the VOD with an account without permissions, probably your own secondary account. To be 100% sure you can momentarily lougout or disable any other microsoft accounts you have.

You have probably already found a solution to this one but just in case :)
