### ISSUE TITLE
YT-dlp error: Exit code 2

### ISSUE THREAD

**Issue by Abstain-Senate-Retype** [kylon/Sharedown#7]
Hello,

when trying to download I video I enter my creds, chromium closes and I get an error:
Download failed
YT-dlp error:
Exit code 2

Added log file below
[sharedownLog.log](https://github.com/kylon/Sharedown/files/7164752/sharedownLog.log)

**Comment by Abstain-Senate-Retype** [comment]
[sharedownLog.log](https://github.com/kylon/Sharedown/files/7164748/sharedownLog.log)

**Comment by kylon** [comment]
it seems you are using an outdated version of yt-dlp

please try again with the latest one: https://github.com/yt-dlp/yt-dlp/releases/tag/2021.09.02
