### ISSUE TITLE
Puppeteer update could decrease install size by 400-500 MB

### ISSUE THREAD

**Issue by muzso** [kylon/Sharedown#72]
Currently Sharedown depends on puppeteer v20.5.0, which pulls down Chrome for Testing v113.0.5672.63:
https://github.com/puppeteer/puppeteer/blob/puppeteer-core-v20.5.0/packages/puppeteer-core/src/revisions.ts

Chrome for Testing did contain (until v115.0.5759.0) a "ClearKeyCdm/_platform_specific/linux_x64/libclearkeycdm.so" file that was 400-500 MB in size, because it was not stripped.

The one in v113.0.5672.63 is 436 MB:
https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/113.0.5672.63/linux64/chrome-linux64.zip

Starting with v115.0.5761.0 the "ClearKeyCdm" directory has been dropped from Chrome for Testing builds alltogether, thus the complete Chrome ZIP size has been reduced drastically.

Puppeteer first adopted this change in its 20.9.0 release:
https://github.com/puppeteer/puppeteer/releases/tag/puppeteer-core-v20.9.0
> roll to Chrome 115.0.5790.98

Thus updating Sharedown to puppeteer v20.9.0 (or anything later) could benefit from this decrease in storage space requirement.

**Comment by kylon** [comment]
thanks for the heads up, will update sharedown
