### ISSUE TITLE
Cannot read properties of undefined (reading '.mediaBaseUrl')

### ISSUE THREAD

**Issue by Dr-Hebz** [kylon/Sharedown#78]
this error come after i enter username and password and the page load for like 15 secs
[sharedownLog.log](https://github.com/kylon/Sharedown/files/13377531/sharedownLog.log)

**Comment by kylon** [comment]
do you see the video player loading page? can you try with a different link? use copy link button in sharepoint

**Comment by Dr-Hebz** [comment]
> do you see the video player loading page? can you try with a different link? use copy link button in sharepoint

okay i tried another link and it worked thanks
