### ISSUE TITLE
Suggestion: Simplify wiki install dependancies on Windows

### ISSUE THREAD

**Issue by sabo-fx** [kylon/Sharedown#83]
**Suggestion**
Simplify wiki install dependancies on Windows

**I'm referring to**
https://github.com/kylon/Sharedown/wiki

I was able to install all dependancies from an elevated powershell terminal using the following commands:
```
winget install ffmpeg
winget install YT-dlp
winget install -e --id Python.Python.3.10 --scope machine
```
![WhatsApp Image 2024-03-07 at 17 26 56_f73590ff](https://github.com/kylon/Sharedown/assets/53176609/c3b9ee69-29e2-4aa5-a318-e1e4250de27b)

One of the benefits of using the 'winget' method is that the _paths for the installed executables are automatically added_.

**Tested on**
Windows 11 Enterprise
Version 23H2 (OS Build 22631.3155)

**Comment by kylon** [comment]
nice, i don't use windows that much and was not aware of winget, thanks

wiki has been updated

**Comment by sabo-fx** [comment]
You're welcome. Glad to be of help. btw, thanks for the shoutout!
