### ISSUE TITLE
no video data found in SP.List.GetListDataAsStream?listFullUrl

### ISSUE THREAD

**Issue by snowcross** [kylon/Sharedown#90]
hi,
after the login process the video starts to play and then I get an error of "no video data found in SP.List.GetListDataAsStream?listFullUrl"
this is when download is set to direct.
I get similar errors when trying the other 2 download types.

**Comment by snowcross** [comment]
here are the logs

fillLoginFieldsFromPwdManager: no credentials found for module 0, skip..

fillLoginFieldsFromPwdManager: no credentials found for module 0, skip..

startDownload: start

startDownload: valid data: true

WARNING: custom chrome executable, Sharedown may not work as expected!

runPuppeteerGetVideoData: goto XXX

_sharepointLogin: start login procedure

_sharepointLogin: has login data

_waitForVideoPlayer: ignore:
Protocol error (DOM.describeNode): Cannot find context with specified id

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

_getDataFromResponseListDataRow: No match for undefined

_makeDirectUrl: no filterlink in vID:
undefined

runPuppeteerGetVideoData: error
no video data found in SP.List.GetListDataAsStream?listFullUrl

downloadVideo: has vdata: false

startDownload: failed
undefined

**Comment by kylon** [comment]
direct only works in few cases, thats expected, what is the error with yt-dlp or ffmpeg?
you get the same error with built-in chrome?

**Comment by snowcross** [comment]
for built-in chrome it can't find the executable.


for ffmpeg I get this error
Unexpected end of JSON input
pptr:evaluate;_getSpItmUrlFromApiRequest%20(%2FUsers%2Fagrant%2FSharedown%2Fpreload.js%3A285%3A27):2:70


here is the log for that. 


startDownload: start

startDownload: valid data: true

_getPuppeteerExecutablePath:
The "path" argument must be of type string. Received undefined

runPuppeteerGetVideoData: error
failed to find chromium executable

downloadVideo: has vdata: false

startDownload: failed
undefined

startDownload: start

startDownload: valid data: true

WARNING: custom chrome executable, Sharedown may not work as expected!

runPuppeteerGetVideoData: goto https://mimecastproduction-my.sharepoint.com/:v:/g/personal/dprotsenko_mimecast_com/EcgvFpgQKupPgNkqPkTawb0BHfVgQ5jM2eblG9KSNjVEsA?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view&web=1

_sharepointLogin: start login procedure

_waitForVideoPlayer: ignore:
Protocol error (DOM.describeNode): Cannot find context with specified id

_waitForVideoPlayer: ignore:
Protocol error (DOM.describeNode): Cannot find context with specified id

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

_waitForVideoPlayer: ignore:
Protocol error (DOM.describeNode): Cannot find context with specified id

runPuppeteerGetVideoData: no json body on catched response: https://mimecastproduction-my.sharepoint.com/personal/dprotsenko_mimecast_com/_api/SP.List.GetListDataAsStream?listFullUrl=%27https%3A%2F%2Fmimecastproduction%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fdprotsenko%5Fmimecast%5Fcom%27&TryNewExperienceSingle=TRUE
Could not load body for this request. This might happen if the request is a preflight request.

runPuppeteerGetVideoData: no json body on catched response: https://mimecastproduction-my.sharepoint.com/personal/dprotsenko_mimecast_com/_api/SP.List.GetListDataAsStream?listFullUrl=%27https%3A%2F%2Fmimecastproduction%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fdprotsenko%5Fmimecast%5Fcom%27&TryNewExperienceSingle=TRUE
Could not load body for this request. This might happen if the request is a preflight request.

_getDataFromResponse: no spItmUrl
vID: undefined

_getDataFromResponseListDataRow: No match for undefined

_getDataFromResponse: no spItmUrl in altRow:
null

_getSpItmUrlFromApiRequest: apiUrl: https://mimecastproduction-my.sharepoint.com/sites/g/_api/web/GetList(@a1)/RenderListDataAsStream?@a1='/:v:/g/personal'&RootFolder=null

runPuppeteerGetVideoData: error
Unexpected end of JSON input
pptr:evaluate;_getSpItmUrlFromApiRequest%20(%2FUsers%2Fagrant%2FSharedown%2Fpreload.js%3A285%3A27):2:70

downloadVideo: has vdata: false

startDownload: failed
undefined

**Comment by snowcross** [comment]
also, I'm running this from "yarn start"  I can't run an unsigned app on my Mac due to profile restrictions.

**Comment by kylon** [comment]
![Screenshot_20240407_131023](https://github.com/kylon/Sharedown/assets/3252255/62403433-2f0c-4fb5-8ac9-bb782b16a5cf)

is this file present in sharedown folder?

do you have chrome folder in path `node_modules/puppeteer/chrome/`

**Comment by snowcross** [comment]
yes .puppeteerrc.cjs is in the folder

and yes node_modules/puppeteer/chrome/ is in my path.
(it wasn't, I added it and tried again) still can't find chrome

**Comment by kylon** [comment]
so chrome was not installed for some reason, the chrome folder must exists and not empty
what os? you got any error when installing dependencies?

**Comment by snowcross** [comment]
No there were no errors on install, also the chrome folder does exist. What kind of structure of files am I looking for in that folder? So so I can verify.

**Comment by snowcross** [comment]
hi, Thanks for that.  it is now finding the built-in chrome and auth is working to get to the video. 

I'm getting another error now when using yt-dlp or ffmpeg
same error in the popup



startDownload: start

startDownload: valid data: true

runPuppeteerGetVideoData: goto https://mimecastproduction-my.sharepoint.com/:v:/g/personal/dprotsenko_mimecast_com/EcgvFpgQKupPgNkqPkTawb0BHfVgQ5jM2eblG9KSNjVEsA?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view&web=1

_sharepointLogin: start login procedure

_waitForVideoPlayer: ignore:
Protocol error (DOM.describeNode): Cannot find context with specified id

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

runPuppeteerGetVideoData: no json body on catched response: https://mimecastproduction-my.sharepoint.com/personal/dprotsenko_mimecast_com/_api/SP.List.GetListDataAsStream?listFullUrl=%27https%3A%2F%2Fmimecastproduction%2Dmy%2Esharepoint%2Ecom%2Fpersonal%2Fdprotsenko%5Fmimecast%5Fcom%2FDocuments%2FRecordings%2FDMARC%20daily%20standup%2D20240405%5F081350%2DMeeting%20Recording%2Emp4%27&TryNewExperienceSingle=TRUE
Could not load body for this request. This might happen if the request is a preflight request.

runPuppeteerGetVideoData: error
Cannot read properties of undefined (reading '.mediaBaseUrl')

downloadVideo: has vdata: false

startDownload: failed
undefined

startDownload: start

startDownload: valid data: true

runPuppeteerGetVideoData: goto https://mimecastproduction-my.sharepoint.com/:v:/g/personal/dprotsenko_mimecast_com/EcgvFpgQKupPgNkqPkTawb0BHfVgQ5jM2eblG9KSNjVEsA?referrer=Teams.TEAMS-ELECTRON&referrerScenario=MeetingChicletGetLink.view.view&web=1

_sharepointLogin: start login procedure

runPuppeteerGetVideoData: error
Cannot read properties of undefined (reading '.mediaBaseUrl')

downloadVideo: has vdata: false

startDownload: failed
undefined

**Comment by kylon** [comment]
i see, are you gettint the link from context menu in sharepoint -> copy link?
if not, try that way

**Comment by snowcross** [comment]
I was not using that way to get the link.
I tried the link form the context menu and I am getting a different error.
here is the log, I tried the different download types, same error pops up



startDownload: start

startDownload: valid data: true

runPuppeteerGetVideoData: goto https://mimecastproduction-my.sharepoint.com/:v:/r/personal/mvanderlee_mimecast_com/Documents/Recordings/DMARC%20daily%20standup-20240409_080852-Meeting%20Recording.mp4?csf=1&web=1&e=QQEYOM&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D

_sharepointLogin: start login procedure

_waitForVideoPlayer: ignore:
Protocol error (DOM.describeNode): Cannot find context with specified id

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

_waitForVideoPlayer: ignore:
Protocol error (DOM.describeNode): Cannot find context with specified id

_waitForVideoPlayer: ignore:
Execution context was destroyed, most likely because of a navigation.

_makeDirectUrl: no filterlink in vID:
/personal/mvanderlee_mimecast_com/Documents/Recordings/DMARC daily standup-20240409_080852-Meeting Recording.mp4

makeDirectUrl:
rootfolder: /personal/mvanderlee_mimecast_com/Documents/Recordings/DMARC daily standup-20240409_080852-Meeting Recording.mp4
webUrl: https:,,mimecastproduction-my.sharepoint.com,personal,mvanderlee_mimecast_com
final: https://mimecastproduction-my.sharepoint.com/personal/mvanderlee_mimecast_com/Documents/Recordings/DMARC daily standup-20240409_080852-Meeting Recording.mp4

runPuppeteerGetVideoData: direct mode: linkAr:
["https:","","mimecastproduction-my.sharepoint.com","personal","mvanderlee_mimecast_com","Documents","Recordings","DMARC daily standup-20240409_080852-Meeting Recording.mp4"]

cookies: ["MSFPC","MicrosoftApplicationsTelemetryDeviceId","ai_session","FedAuth","isso","SIMI","rtFa"]

downloadVideo: has vdata: true

startDownload: selected 95a3cc3d58

YT-dlp: download failed:
Exit code: 1

DownloadFail event:
YT-dlp error:

Exit code: 1

stopDownload: called

stopDownload: error
Failed to send kill signal to download process

startDownload: start

startDownload: valid data: true

runPuppeteerGetVideoData: goto https://mimecastproduction-my.sharepoint.com/:v:/r/personal/mvanderlee_mimecast_com/Documents/Recordings/DMARC%20daily%20standup-20240409_080852-Meeting%20Recording.mp4?csf=1&web=1&e=QQEYOM&nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJTdHJlYW1XZWJBcHAiLCJyZWZlcnJhbFZpZXciOiJTaGFyZURpYWxvZy1MaW5rIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXcifX0%3D

_sharepointLogin: start login procedure

_makeDirectUrl: no filterlink in vID:
/personal/mvanderlee_mimecast_com/Documents/Recordings/DMARC daily standup-20240409_080852-Meeting Recording.mp4

makeDirectUrl:
rootfolder: /personal/mvanderlee_mimecast_com/Documents/Recordings/DMARC daily standup-20240409_080852-Meeting Recording.mp4
webUrl: https:,,mimecastproduction-my.sharepoint.com,personal,mvanderlee_mimecast_com
final: https://mimecastproduction-my.sharepoint.com/personal/mvanderlee_mimecast_com/Documents/Recordings/DMARC daily standup-20240409_080852-Meeting Recording.mp4

runPuppeteerGetVideoData: direct mode: linkAr:
["https:","","mimecastproduction-my.sharepoint.com","personal","mvanderlee_mimecast_com","Documents","Recordings","DMARC daily standup-20240409_080852-Meeting Recording.mp4"]

cookies: ["ai_session","MSFPC","FedAuth","isso","SIMI","rtFa"]

downloadVideo: has vdata: true

startDownload: selected 95a3cc3d58

YT-dlp: download failed:
Exit code: 1

DownloadFail event:
YT-dlp error:

Exit code: 1

stopDownload: called

stopDownload: error
Failed to send kill signal to download process

**Comment by kylon** [comment]
can you post yt-dlp log? is there an error if you try yt-dlp or ffmpeg, ie not direct?

**Comment by snowcross** [comment]
it works using yt-dlp now !   thanks!!

**Comment by kylon** [comment]
so can be closed?
