### ISSUE TITLE
can not download video suddenly 

### ISSUE THREAD

**Issue by yemichi9** [kylon/Sharedown#91]
![error](https://github.com/kylon/Sharedown/assets/136466785/5bcdeed7-577d-4de9-8d4e-f94d6b5d708b)

can not download video suddenly , error as above

**Comment by kylon** [comment]
you mean with 5.3.3? this is a regression?

**Comment by yemichi9** [comment]
Sorry I don't get it 
All things went good but started from yesterday the error appeared whenever after logging in the school account. The error popped up just a few second after the video start.I did not change any setting or else

**Comment by kylon** [comment]
what sharedown version?

**Comment by yemichi9** [comment]
![image](https://github.com/kylon/Sharedown/assets/136466785/271b9bd3-b7cd-4823-8c4a-9b6a4eb1fdfc)

I just reinstall version 5.3.3 and appear the above error

Thank you

**Comment by kylon** [comment]
are you using a custom chrome browser? can you post a log?

**Comment by yemichi9** [comment]
I use standard chrome browser with some extension module like other video downloader/VPN etc

Here is the Log:
startDownload: start

startDownload: valid data: true

WARNING: custom chrome executable, Sharedown may not work as expected!

runPuppeteerGetVideoData: goto https://studenthkccpolyuedu-my.sharepoint.com/:v:/g/personal/wyyeung_common_cpce-polyu_edu_hk/EZxZeHMuDQBNtge557MbjUkBBZI94bBSJnb8O0v-bGPo4w?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=k92GCS&web=1

_sharepointLogin: start login procedure

_sharepointLogin: has login data

_sharepointLogin: has msid

_sharepointLogin: has auto-login

_getDataFromResponse: no spItmUrl
vID: undefined

_getDataFromResponseListDataRow: No match for undefined

_getDataFromResponse: no spItmUrl in altRow:
null

_getSpItmUrlFromApiRequest: apiUrl: https://studenthkccpolyuedu-my.sharepoint.com/sites/g/_api/web/GetList(@a1)/RenderListDataAsStream?@a1='/:v:/g/personal'&RootFolder=null

runPuppeteerGetVideoData: error
Unexpected end of JSON input
pptr:evaluate;_getSpItmUrlFromApiRequest%20(C%3A%5CUsers%5Cuser%5CAppData%5CLocal%5CPrograms%5Csharedown%5Cresources%5Capp.asar%5Cpreload.js%3A286%3A27):2:70

downloadVideo: has vdata: false

startDownload: failed
undefined

**Comment by kylon** [comment]
can you please try with built-in chrome, external browser can cause issues, that option exists as an emergency option
also try to get the link from sharepoint context menu -> copy link, if you are using a different method

**Comment by yemichi9** [comment]
I have sucessfully download a video by getting the link from sharepoint context menu. It works! thank you with your kind help!!

**Comment by EndersDev** [comment]
I just wanted to say that I did everything as this video: https://www.youtube.com/watch?v=lrlaxTnmJJc

got the error :unexpected end of json input

and them when i got the link of the video in this button: 
![image](https://github.com/kylon/Sharedown/assets/54655640/6a0d5b00-609e-41cd-8c88-1e002f47beac)

It Worked !!

Thank you!!
