### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by Yellow-Cactus** [kylon/Sharedown#95]
![Schermafbeelding 2024-06-20 114003](https://github.com/kylon/Sharedown/assets/173355926/9be97985-6643-4872-85cf-838a4f0bd9f1)
I got this when i wanted to download a video. How do i fix this?

**Comment by kylon** [comment]
can you post a log?

**Comment by Yellow-Cactus** [comment]
Where can i find the log?

**Comment by kylon** [comment]
file menu

**Comment by Yellow-Cactus** [comment]
![Schermafbeelding 2024-06-20 120704](https://github.com/kylon/Sharedown/assets/173355926/b76744bf-fe15-4b57-b445-e84aeb0d9269)

**Comment by kylon** [comment]
enable logs in sharedown settings

**Comment by Yellow-Cactus** [comment]
![image](https://github.com/kylon/Sharedown/assets/173355926/f93e5555-372a-46e7-b850-c45740884830)

**Comment by Yellow-Cactus** [comment]
Hey, do you know how to fix it?

**Comment by kylon** [comment]
are you getting the link from sharepoint context menu->copy link?

**Comment by Yellow-Cactus** [comment]
No, but i tried it and now it works. Thank You!
